#!/bin/sh
# build-site: build a website from a collection of R Notebooks (html_notebook) in notebooks/
# assumes: script exists and runs in top-level project directory
#          .build is only used by build-site
#          _site-HEAD.yml, _site-TAIL.yml, and index.Rmd are properly built in notebooks/
#          all other .Rmd files in notebooks/ are either html_notebook or html_document
# results: all .Rmd files other than index.Rmd are included in the "Notebooks" menu in file alphabetical order
set -e

NB="html_notebook"
DOC="html_document"

if [ ! -x build-site ]
then
	echo "error: not running 'build-site' from its directory!"
	exit 1
fi

if [ ! -d .build ]
then
	mkdir .build
fi

cat notebooks/_site-HEAD.yml >.build/_site.yml

for n in notebooks/*.Rmd
do
	NAME=`basename ${n}`
	YAML=`cat ${n} | grep -n "\---" | head -2 | tail -1 | awk -F ':' '{print $1}'`

	if [ "$NAME" != "index.Rmd" ]
	then
		TEXT=`cat ${n} | grep "^title: " | head -1 | awk -F '"' '{print $2}'`
		HREF="${NAME/.Rmd/.html}"
		echo "      - text: \"${TEXT}\"" >>.build/_site.yml
		echo "        href: ${HREF}" >>.build/_site.yml
	fi

	cat ${n} | sed -e "1,${YAML}s/${NB}/${DOC}/" >.build/${NAME}
done

cat notebooks/_site-TAIL.yml >>.build/_site.yml

Rscript -e 'rmarkdown::render_site(".build")'
