---
title: "Constraints vs Performance"
author: "John Benninghoff"
date: '2024-04-30'
date-modified: '2024-04-30'
categories: notes
order: 107
output:
  html_notebook:
    theme:
      version: 5
      preset: bootstrap
    css: assets/extra.css
    pandoc_args: --shift-heading-level-by=1
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
---

Visualizations exploring the use of constraints vs performance improvements in risk management.

# Questions/TODO

- [ ] Questions/TODO list here

```{r setup, message = FALSE, warning = FALSE}
library(ggplot2)
library(jbplot)
```

# Normal Performance

Replicate a version of Figure 9 from the
[Safety-II White Paper](https://www.england.nhs.uk/signuptosafety/wp-content/uploads/sites/16/2015/10/safety-1-safety-2-whte-papr.pdf),
with help from <https://ggplot2tutor.com/tutorials/sampling_distributions>:

```{r fig9}
ggplot(data.frame(x = c(-3, 3)), aes(x)) +
  stat_function(fun = dnorm, geom = "line") +
  stat_function(fun = dnorm, geom = "area", fill = "red", xlim = c(-3, -2)) +
  scale_x_continuous(breaks = -3:3, minor_breaks = NULL) +
  labs(x = NULL, y = NULL) +
  theme_quo(minor.y = FALSE) +
  theme(axis.text.y = element_blank())
```
